[meta]
name     = "Archivist"
author   = "XertroV"
category = "Replay"
version  = "0.1.2"
siteid   = 328

[script]
#__DEFINES__
dependencies = ["MLHook", "NadeoServices"]
# , "VehicleState"
module = "Archivist"
exports = ["Exports/ArchivistFunctions.as"]
shared_exports = ["Exports/ArchivistShared.as"]
