[meta]
name     = "Archivist"
author   = "XertroV"
category = "Replay"
version  = "0.1.0"
siteid   = 328

[script]
#__DEFINES__
dependencies = ["MLHook", "NadeoServices"]
optional_dependencies = ["HttpServer", "httpserver-dev"]
# , "VehicleState"
